services:
  web-app-automated:
    image: node:18-slim
    container_name: nextjs_devops_app
    ports:
      - "8081:3000"
    volumes:
      - .:/app  # The code fetched by Jenkins is mounted here
    working_dir: /app
    command: sh -c "npm install && npm run dev"
