services:
  web-app-automated:
    image: node:18-slim
    container_name: jenkins-container
    ports:
      - "8081:3000"
    volumes:
      - .:/app  # The code fetched by Jenkins is mounted at this place
    working_dir: /app
    command: sh -c "npm install && npx next dev -H 0.0.0.0"
