services:
  web-app-automated:
    image: node:18-slim
    container_name: jenkins-app-container
    ports:
      - "8081:3000"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    command: >
      sh -c "npm install &&
             npx next dev -H 0.0.0.0" &&
             npm start"
